services:
  db:
    image: postgres:15
    container_name: saiyajin-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: saiyajin
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - saiyajin-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: saiyajin-backend
    depends_on:
      - db
    environment:
      PORT: ${PORT}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - ${PORT}:${PORT}
    networks:
      - saiyajin-network

#frontend:
#  build:
#   context: ./frontend/saijainstore
#   dockerfile: Dockerfile
#   args:
#      FRONTEND_BACKEND_URL: ${FRONTEND_BACKEND_URL}
#  container_name: saiyajin-frontend
#  ports:
#    - "${FRONTEND_PORT}:80"
#  depends_on:
#    - backend
#  networks:
#   - saiyajin-network

volumes:
  postgres-data:


networks:
  saiyajin-network:
    driver: bridge
